/**
 * Re-export of generated backend types for easy consumption across the app.
 * Source: src/frontend/src/backend.d.ts (auto-generated by pnpm bindgen).
 *
 * NOTE: The currently bound backend only exposes the waitlist surface.
 * As the vault/deposit/goal/notification/admin methods are bound via
 * `pnpm bindgen`, their types will appear here automatically. Importing
 * app code should always pull types from this file (`@/types/backend`)
 * rather than reaching into `@/backend` directly.
 */
import type { Principal } from "@icp-sdk/core/principal";

export type {
  Some,
  None,
  Option,
  Entry,
  Timestamp,
  Email,
  backendInterface,
} from "@/backend";

/** Principal re-export so callers don't need a second import site. */
export type { Principal };

/**
 * VaultStatus — mirrors the backend variant once bound.
 * Declared locally so UI components can be built ahead of bindgen.
 */
export type VaultStatus = "freezing" | "thawing" | "thawed" | "broken";

/**
 * Vault — local UI shape for CryoVaultCard. The real backend record
 * will replace this once `pnpm bindgen` runs; field names are chosen
 * to match the planned backend schema.
 */
export interface Vault {
  id: string;
  goalName: string;
  currentAmount: bigint;
  targetAmount: bigint;
  unlockAt: bigint; // nanos since epoch
  lockedAt: bigint;
  status: VaultStatus;
}

/** Notification kind for CryoNotification. */
export type NotificationKind = "success" | "warning" | "info";
