/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Email = IDL.Text;
export const Timestamp = IDL.Int;
export const CreateVaultRequest = IDL.Record({
  'goalName' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'lockDurationNs' : Timestamp,
  'targetAmount' : IDL.Nat,
});
export const Achievement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : UserId,
  'description' : IDL.Text,
  'awardedAt' : Timestamp,
});
export const JobStatus = IDL.Variant({
  'deadLetter' : IDL.Null,
  'pending' : IDL.Null,
  'failed' : IDL.Null,
  'running' : IDL.Null,
  'succeeded' : IDL.Null,
});
export const IdempotencyKey = IDL.Text;
export const JobKind = IDL.Variant({
  'unlockCheck' : IDL.Null,
  'recurringDeposit' : IDL.Null,
  'interestReward' : IDL.Null,
  'autoDeposit' : IDL.Null,
  'optimizationRun' : IDL.Null,
  'withdrawalProcess' : IDL.Null,
  'milestoneCheck' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'idempotencyKey' : IdempotencyKey,
  'nextAttemptAt' : Timestamp,
  'kind' : JobKind,
  'createdAt' : Timestamp,
  'retryCount' : IDL.Nat,
  'lastError' : IDL.Opt(IDL.Text),
  'payload' : IDL.Text,
});
export const Milestone = IDL.Variant({
  'fifty' : IDL.Null,
  'seventyFive' : IDL.Null,
  'oneHundred' : IDL.Null,
  'twentyFive' : IDL.Null,
});
export const GoalProgress = IDL.Record({
  'reachedMilestones' : IDL.Vec(Milestone),
  'percent' : IDL.Nat,
  'targetAmount' : IDL.Nat,
  'vaultId' : IDL.Nat,
  'currentAmount' : IDL.Nat,
  'nextMilestone' : IDL.Opt(Milestone),
});
export const GrowthAnalytics = IDL.Record({
  'newUsersLast30d' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalSavedAcrossVaults' : IDL.Nat,
  'averageVaultsPerUser' : IDL.Float64,
  'newUsersLast7d' : IDL.Nat,
});
export const JobLogEntry = IDL.Record({
  'status' : JobStatus,
  'attempt' : IDL.Nat,
  'jobId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const AdminMetrics = IDL.Record({
  'deadLetterJobs' : IDL.Nat,
  'totalVaults' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'waitlistCount' : IDL.Nat,
  'pendingJobs' : IDL.Nat,
  'totalDeposits' : IDL.Nat,
});
export const ReachedMilestone = IDL.Record({
  'percent' : IDL.Nat,
  'vaultId' : IDL.Nat,
  'milestone' : Milestone,
  'reachedAt' : Timestamp,
});
export const IdentityProvider = IDL.Variant({
  'internetIdentity' : IDL.Null,
  'apple' : IDL.Null,
  'google' : IDL.Null,
  'email' : IDL.Null,
});
export const UserIdentity = IDL.Record({
  'principal' : UserId,
  'provider' : IdentityProvider,
  'isAdmin' : IDL.Bool,
  'registeredAt' : Timestamp,
});
export const NotificationType = IDL.Variant({
  'recommendationAvailable' : IDL.Null,
  'unlockApproaching' : IDL.Null,
  'vaultUnlocked' : IDL.Null,
  'milestoneReached' : IDL.Null,
  'depositFrozen' : IDL.Null,
  'adminBroadcast' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'vaultId' : IDL.Opt(IDL.Nat),
});
export const Recommendation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'rationale' : IDL.Text,
  'cashFlowWarning' : IDL.Opt(IDL.Text),
  'disclaimer' : IDL.Text,
  'suggestedPercent' : IDL.Nat,
  'suggestedDepositAdjustment' : IDL.Opt(
    IDL.Record({ 'newAmount' : IDL.Nat, 'vaultId' : IDL.Nat })
  ),
});
export const RecurringCadence = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const RecurringDeposit = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'idempotencyKeyPrefix' : IdempotencyKey,
  'nextRunAt' : Timestamp,
  'vaultId' : IDL.Nat,
  'cadence' : RecurringCadence,
  'amount' : IDL.Nat,
});
export const VaultStatus = IDL.Variant({
  'broken' : IDL.Null,
  'freezing' : IDL.Null,
  'thawed' : IDL.Null,
  'thawing' : IDL.Null,
});
export const VaultView = IDL.Record({
  'id' : IDL.Nat,
  'status' : VaultStatus,
  'unlockDate' : Timestamp,
  'goalName' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'progressPercent' : IDL.Nat,
  'targetAmount' : IDL.Nat,
  'currentAmount' : IDL.Nat,
});
export const EntrySide = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Sequence = IDL.Nat;
export const EntryReason = IDL.Variant({
  'recurringDeposit' : IDL.Null,
  'vaultLock' : IDL.Null,
  'interestReward' : IDL.Null,
  'manualDeposit' : IDL.Null,
  'vaultUnlock' : IDL.Null,
  'jobProcessing' : IDL.Null,
  'withdrawal' : IDL.Null,
  'reconciliationAdjustment' : IDL.Null,
  'vaultBreak' : IDL.Null,
});
export const LedgerEntry = IDL.Record({
  'idempotencyKey' : IdempotencyKey,
  'userId' : UserId,
  'side' : EntrySide,
  'description' : IDL.Text,
  'triggeredBy' : UserId,
  'vaultId' : IDL.Nat,
  'timestamp' : Timestamp,
  'amount' : IDL.Nat,
  'sequence' : Sequence,
  'transactionId' : IDL.Nat,
  'reason' : EntryReason,
});
export const VaultStats = IDL.Record({
  'status' : IDL.Text,
  'depositCount' : IDL.Nat,
  'goalName' : IDL.Text,
  'userId' : UserId,
  'targetAmount' : IDL.Nat,
  'vaultId' : IDL.Nat,
  'currentAmount' : IDL.Nat,
});
export const Entry = IDL.Record({ 'email' : Email, 'timestamp' : Timestamp });
export const DepositResult = IDL.Variant({
  'ok' : IDL.Record({ 'newBalance' : IDL.Nat, 'transactionId' : IDL.Nat }),
  'insufficientReason' : IDL.Null,
  'duplicate' : IDL.Null,
  'invalidVault' : IDL.Null,
});
export const ReconciliationResult = IDL.Record({
  'sumCredits' : IDL.Nat,
  'sumDebits' : IDL.Nat,
  'userId' : UserId,
  'vaultId' : IDL.Nat,
  'derivedBalance' : IDL.Nat,
  'balanced' : IDL.Bool,
});
export const SetupRecurringDepositRequest = IDL.Record({
  'idempotencyKeyPrefix' : IdempotencyKey,
  'vaultId' : IDL.Nat,
  'cadence' : RecurringCadence,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([UserId], [IDL.Bool], []),
  'addToWaitlist' : IDL.Func([Email], [IDL.Bool], []),
  'cancelRecurringDeposit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createVault' : IDL.Func([CreateVaultRequest], [IDL.Nat], []),
  'emailAlreadyExists' : IDL.Func([Email], [IDL.Bool], ['query']),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], []),
  'getDeadLetterJobs' : IDL.Func([], [IDL.Vec(Job)], []),
  'getEmailTimestamp' : IDL.Func([IDL.Text], [IDL.Opt(Timestamp)], ['query']),
  'getGoalProgress' : IDL.Func([IDL.Nat], [GoalProgress], []),
  'getGrowthAnalytics' : IDL.Func([], [GrowthAnalytics], []),
  'getJobLog' : IDL.Func([], [IDL.Vec(JobLogEntry)], []),
  'getMetrics' : IDL.Func([], [AdminMetrics], []),
  'getMilestones' : IDL.Func([IDL.Nat], [IDL.Vec(ReachedMilestone)], []),
  'getMyIdentity' : IDL.Func([], [UserIdentity], []),
  'getMyPrincipal' : IDL.Func([], [IDL.Text], []),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
  'getPendingJobCount' : IDL.Func([], [IDL.Nat], []),
  'getRecommendationHistory' : IDL.Func([], [IDL.Vec(Recommendation)], []),
  'getRecommendations' : IDL.Func([], [Recommendation], []),
  'getRecurringDeposits' : IDL.Func([], [IDL.Vec(RecurringDeposit)], []),
  'getVault' : IDL.Func([IDL.Nat], [IDL.Opt(VaultView)], []),
  'getVaultLedger' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], []),
  'getVaultStats' : IDL.Func([], [IDL.Vec(VaultStats)], []),
  'getVaults' : IDL.Func([], [IDL.Vec(VaultView)], []),
  'getWaitlist' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], []),
  'makeDeposit' : IDL.Func(
      [IDL.Nat, IDL.Nat, IdempotencyKey, IDL.Text],
      [DepositResult],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
  'markRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'reconcileMyVaults' : IDL.Func([], [IDL.Vec(ReconciliationResult)], []),
  'reconcileVault' : IDL.Func([IDL.Nat], [ReconciliationResult], []),
  'setupRecurringDeposit' : IDL.Func(
      [SetupRecurringDepositRequest],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Email = IDL.Text;
  const Timestamp = IDL.Int;
  const CreateVaultRequest = IDL.Record({
    'goalName' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'lockDurationNs' : Timestamp,
    'targetAmount' : IDL.Nat,
  });
  const Achievement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : UserId,
    'description' : IDL.Text,
    'awardedAt' : Timestamp,
  });
  const JobStatus = IDL.Variant({
    'deadLetter' : IDL.Null,
    'pending' : IDL.Null,
    'failed' : IDL.Null,
    'running' : IDL.Null,
    'succeeded' : IDL.Null,
  });
  const IdempotencyKey = IDL.Text;
  const JobKind = IDL.Variant({
    'unlockCheck' : IDL.Null,
    'recurringDeposit' : IDL.Null,
    'interestReward' : IDL.Null,
    'autoDeposit' : IDL.Null,
    'optimizationRun' : IDL.Null,
    'withdrawalProcess' : IDL.Null,
    'milestoneCheck' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'idempotencyKey' : IdempotencyKey,
    'nextAttemptAt' : Timestamp,
    'kind' : JobKind,
    'createdAt' : Timestamp,
    'retryCount' : IDL.Nat,
    'lastError' : IDL.Opt(IDL.Text),
    'payload' : IDL.Text,
  });
  const Milestone = IDL.Variant({
    'fifty' : IDL.Null,
    'seventyFive' : IDL.Null,
    'oneHundred' : IDL.Null,
    'twentyFive' : IDL.Null,
  });
  const GoalProgress = IDL.Record({
    'reachedMilestones' : IDL.Vec(Milestone),
    'percent' : IDL.Nat,
    'targetAmount' : IDL.Nat,
    'vaultId' : IDL.Nat,
    'currentAmount' : IDL.Nat,
    'nextMilestone' : IDL.Opt(Milestone),
  });
  const GrowthAnalytics = IDL.Record({
    'newUsersLast30d' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalSavedAcrossVaults' : IDL.Nat,
    'averageVaultsPerUser' : IDL.Float64,
    'newUsersLast7d' : IDL.Nat,
  });
  const JobLogEntry = IDL.Record({
    'status' : JobStatus,
    'attempt' : IDL.Nat,
    'jobId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const AdminMetrics = IDL.Record({
    'deadLetterJobs' : IDL.Nat,
    'totalVaults' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'waitlistCount' : IDL.Nat,
    'pendingJobs' : IDL.Nat,
    'totalDeposits' : IDL.Nat,
  });
  const ReachedMilestone = IDL.Record({
    'percent' : IDL.Nat,
    'vaultId' : IDL.Nat,
    'milestone' : Milestone,
    'reachedAt' : Timestamp,
  });
  const IdentityProvider = IDL.Variant({
    'internetIdentity' : IDL.Null,
    'apple' : IDL.Null,
    'google' : IDL.Null,
    'email' : IDL.Null,
  });
  const UserIdentity = IDL.Record({
    'principal' : UserId,
    'provider' : IdentityProvider,
    'isAdmin' : IDL.Bool,
    'registeredAt' : Timestamp,
  });
  const NotificationType = IDL.Variant({
    'recommendationAvailable' : IDL.Null,
    'unlockApproaching' : IDL.Null,
    'vaultUnlocked' : IDL.Null,
    'milestoneReached' : IDL.Null,
    'depositFrozen' : IDL.Null,
    'adminBroadcast' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : UserId,
    'notificationType' : NotificationType,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'vaultId' : IDL.Opt(IDL.Nat),
  });
  const Recommendation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'rationale' : IDL.Text,
    'cashFlowWarning' : IDL.Opt(IDL.Text),
    'disclaimer' : IDL.Text,
    'suggestedPercent' : IDL.Nat,
    'suggestedDepositAdjustment' : IDL.Opt(
      IDL.Record({ 'newAmount' : IDL.Nat, 'vaultId' : IDL.Nat })
    ),
  });
  const RecurringCadence = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const RecurringDeposit = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'idempotencyKeyPrefix' : IdempotencyKey,
    'nextRunAt' : Timestamp,
    'vaultId' : IDL.Nat,
    'cadence' : RecurringCadence,
    'amount' : IDL.Nat,
  });
  const VaultStatus = IDL.Variant({
    'broken' : IDL.Null,
    'freezing' : IDL.Null,
    'thawed' : IDL.Null,
    'thawing' : IDL.Null,
  });
  const VaultView = IDL.Record({
    'id' : IDL.Nat,
    'status' : VaultStatus,
    'unlockDate' : Timestamp,
    'goalName' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'progressPercent' : IDL.Nat,
    'targetAmount' : IDL.Nat,
    'currentAmount' : IDL.Nat,
  });
  const EntrySide = IDL.Variant({ 'credit' : IDL.Null, 'debit' : IDL.Null });
  const Sequence = IDL.Nat;
  const EntryReason = IDL.Variant({
    'recurringDeposit' : IDL.Null,
    'vaultLock' : IDL.Null,
    'interestReward' : IDL.Null,
    'manualDeposit' : IDL.Null,
    'vaultUnlock' : IDL.Null,
    'jobProcessing' : IDL.Null,
    'withdrawal' : IDL.Null,
    'reconciliationAdjustment' : IDL.Null,
    'vaultBreak' : IDL.Null,
  });
  const LedgerEntry = IDL.Record({
    'idempotencyKey' : IdempotencyKey,
    'userId' : UserId,
    'side' : EntrySide,
    'description' : IDL.Text,
    'triggeredBy' : UserId,
    'vaultId' : IDL.Nat,
    'timestamp' : Timestamp,
    'amount' : IDL.Nat,
    'sequence' : Sequence,
    'transactionId' : IDL.Nat,
    'reason' : EntryReason,
  });
  const VaultStats = IDL.Record({
    'status' : IDL.Text,
    'depositCount' : IDL.Nat,
    'goalName' : IDL.Text,
    'userId' : UserId,
    'targetAmount' : IDL.Nat,
    'vaultId' : IDL.Nat,
    'currentAmount' : IDL.Nat,
  });
  const Entry = IDL.Record({ 'email' : Email, 'timestamp' : Timestamp });
  const DepositResult = IDL.Variant({
    'ok' : IDL.Record({ 'newBalance' : IDL.Nat, 'transactionId' : IDL.Nat }),
    'insufficientReason' : IDL.Null,
    'duplicate' : IDL.Null,
    'invalidVault' : IDL.Null,
  });
  const ReconciliationResult = IDL.Record({
    'sumCredits' : IDL.Nat,
    'sumDebits' : IDL.Nat,
    'userId' : UserId,
    'vaultId' : IDL.Nat,
    'derivedBalance' : IDL.Nat,
    'balanced' : IDL.Bool,
  });
  const SetupRecurringDepositRequest = IDL.Record({
    'idempotencyKeyPrefix' : IdempotencyKey,
    'vaultId' : IDL.Nat,
    'cadence' : RecurringCadence,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([UserId], [IDL.Bool], []),
    'addToWaitlist' : IDL.Func([Email], [IDL.Bool], []),
    'cancelRecurringDeposit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createVault' : IDL.Func([CreateVaultRequest], [IDL.Nat], []),
    'emailAlreadyExists' : IDL.Func([Email], [IDL.Bool], ['query']),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], []),
    'getDeadLetterJobs' : IDL.Func([], [IDL.Vec(Job)], []),
    'getEmailTimestamp' : IDL.Func([IDL.Text], [IDL.Opt(Timestamp)], ['query']),
    'getGoalProgress' : IDL.Func([IDL.Nat], [GoalProgress], []),
    'getGrowthAnalytics' : IDL.Func([], [GrowthAnalytics], []),
    'getJobLog' : IDL.Func([], [IDL.Vec(JobLogEntry)], []),
    'getMetrics' : IDL.Func([], [AdminMetrics], []),
    'getMilestones' : IDL.Func([IDL.Nat], [IDL.Vec(ReachedMilestone)], []),
    'getMyIdentity' : IDL.Func([], [UserIdentity], []),
    'getMyPrincipal' : IDL.Func([], [IDL.Text], []),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], []),
    'getPendingJobCount' : IDL.Func([], [IDL.Nat], []),
    'getRecommendationHistory' : IDL.Func([], [IDL.Vec(Recommendation)], []),
    'getRecommendations' : IDL.Func([], [Recommendation], []),
    'getRecurringDeposits' : IDL.Func([], [IDL.Vec(RecurringDeposit)], []),
    'getVault' : IDL.Func([IDL.Nat], [IDL.Opt(VaultView)], []),
    'getVaultLedger' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], []),
    'getVaultStats' : IDL.Func([], [IDL.Vec(VaultStats)], []),
    'getVaults' : IDL.Func([], [IDL.Vec(VaultView)], []),
    'getWaitlist' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], []),
    'makeDeposit' : IDL.Func(
        [IDL.Nat, IDL.Nat, IdempotencyKey, IDL.Text],
        [DepositResult],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([], [IDL.Nat], []),
    'markRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reconcileMyVaults' : IDL.Func([], [IDL.Vec(ReconciliationResult)], []),
    'reconcileVault' : IDL.Func([IDL.Nat], [ReconciliationResult], []),
    'setupRecurringDeposit' : IDL.Func(
        [SetupRecurringDepositRequest],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };