/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'id' : bigint,
  'title' : string,
  'userId' : UserId,
  'description' : string,
  'awardedAt' : Timestamp,
}
export interface AdminMetrics {
  'deadLetterJobs' : bigint,
  'totalVaults' : bigint,
  'totalUsers' : bigint,
  'waitlistCount' : bigint,
  'pendingJobs' : bigint,
  'totalDeposits' : bigint,
}
export interface CreateVaultRequest {
  'goalName' : string,
  'note' : [] | [string],
  'lockDurationNs' : Timestamp,
  'targetAmount' : bigint,
}
export type DepositResult = {
    'ok' : { 'newBalance' : bigint, 'transactionId' : bigint }
  } |
  { 'insufficientReason' : null } |
  { 'duplicate' : null } |
  { 'invalidVault' : null };
export type Email = string;
export interface Entry { 'email' : Email, 'timestamp' : Timestamp }
export type EntryReason = { 'recurringDeposit' : null } |
  { 'vaultLock' : null } |
  { 'interestReward' : null } |
  { 'manualDeposit' : null } |
  { 'vaultUnlock' : null } |
  { 'jobProcessing' : null } |
  { 'withdrawal' : null } |
  { 'reconciliationAdjustment' : null } |
  { 'vaultBreak' : null };
export type EntrySide = { 'credit' : null } |
  { 'debit' : null };
export interface GoalProgress {
  'reachedMilestones' : Array<Milestone>,
  'percent' : bigint,
  'targetAmount' : bigint,
  'vaultId' : bigint,
  'currentAmount' : bigint,
  'nextMilestone' : [] | [Milestone],
}
export interface GrowthAnalytics {
  'newUsersLast30d' : bigint,
  'totalUsers' : bigint,
  'totalSavedAcrossVaults' : bigint,
  'averageVaultsPerUser' : number,
  'newUsersLast7d' : bigint,
}
export type IdempotencyKey = string;
export type IdentityProvider = { 'internetIdentity' : null } |
  { 'apple' : null } |
  { 'google' : null } |
  { 'email' : null };
export interface Job {
  'id' : bigint,
  'status' : JobStatus,
  'idempotencyKey' : IdempotencyKey,
  'nextAttemptAt' : Timestamp,
  'kind' : JobKind,
  'createdAt' : Timestamp,
  'retryCount' : bigint,
  'lastError' : [] | [string],
  'payload' : string,
}
export type JobKind = { 'unlockCheck' : null } |
  { 'recurringDeposit' : null } |
  { 'interestReward' : null } |
  { 'autoDeposit' : null } |
  { 'optimizationRun' : null } |
  { 'withdrawalProcess' : null } |
  { 'milestoneCheck' : null };
export interface JobLogEntry {
  'status' : JobStatus,
  'attempt' : bigint,
  'jobId' : bigint,
  'message' : string,
  'timestamp' : Timestamp,
}
export type JobStatus = { 'deadLetter' : null } |
  { 'pending' : null } |
  { 'failed' : null } |
  { 'running' : null } |
  { 'succeeded' : null };
export interface LedgerEntry {
  'idempotencyKey' : IdempotencyKey,
  'userId' : UserId,
  'side' : EntrySide,
  'description' : string,
  'triggeredBy' : UserId,
  'vaultId' : bigint,
  'timestamp' : Timestamp,
  'amount' : bigint,
  'sequence' : Sequence,
  'transactionId' : bigint,
  'reason' : EntryReason,
}
export type Milestone = { 'fifty' : null } |
  { 'seventyFive' : null } |
  { 'oneHundred' : null } |
  { 'twentyFive' : null };
export interface Notification {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'userId' : UserId,
  'notificationType' : NotificationType,
  'createdAt' : Timestamp,
  'read' : boolean,
  'vaultId' : [] | [bigint],
}
export type NotificationType = { 'recommendationAvailable' : null } |
  { 'unlockApproaching' : null } |
  { 'vaultUnlocked' : null } |
  { 'milestoneReached' : null } |
  { 'depositFrozen' : null } |
  { 'adminBroadcast' : null };
export interface ReachedMilestone {
  'percent' : bigint,
  'vaultId' : bigint,
  'milestone' : Milestone,
  'reachedAt' : Timestamp,
}
export interface Recommendation {
  'id' : bigint,
  'title' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'rationale' : string,
  'cashFlowWarning' : [] | [string],
  'disclaimer' : string,
  'suggestedPercent' : bigint,
  'suggestedDepositAdjustment' : [] | [
    { 'newAmount' : bigint, 'vaultId' : bigint }
  ],
}
export interface ReconciliationResult {
  'sumCredits' : bigint,
  'sumDebits' : bigint,
  'userId' : UserId,
  'vaultId' : bigint,
  'derivedBalance' : bigint,
  'balanced' : boolean,
}
export type RecurringCadence = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface RecurringDeposit {
  'id' : bigint,
  'active' : boolean,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'idempotencyKeyPrefix' : IdempotencyKey,
  'nextRunAt' : Timestamp,
  'vaultId' : bigint,
  'cadence' : RecurringCadence,
  'amount' : bigint,
}
export type Sequence = bigint;
export interface SetupRecurringDepositRequest {
  'idempotencyKeyPrefix' : IdempotencyKey,
  'vaultId' : bigint,
  'cadence' : RecurringCadence,
  'amount' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserIdentity {
  'principal' : UserId,
  'provider' : IdentityProvider,
  'isAdmin' : boolean,
  'registeredAt' : Timestamp,
}
export interface VaultStats {
  'status' : string,
  'depositCount' : bigint,
  'goalName' : string,
  'userId' : UserId,
  'targetAmount' : bigint,
  'vaultId' : bigint,
  'currentAmount' : bigint,
}
export type VaultStatus = { 'broken' : null } |
  { 'freezing' : null } |
  { 'thawed' : null } |
  { 'thawing' : null };
export interface VaultView {
  'id' : bigint,
  'status' : VaultStatus,
  'unlockDate' : Timestamp,
  'goalName' : string,
  'note' : [] | [string],
  'createdAt' : Timestamp,
  'progressPercent' : bigint,
  'targetAmount' : bigint,
  'currentAmount' : bigint,
}
/**
 * / Froze backend — composition root.
 * /
 * / Wires all domain modules together via mixins. No business logic lives
 * / here; every public function is delegated to a mixin. Stable state is
 * / declared here and passed into the mixins that need it.
 * /
 * / State shape change from the previous waitlist-only actor requires an
 * / explicit migration (see migration.mo).
 */
export interface _SERVICE {
  'addAdmin' : ActorMethod<[UserId], boolean>,
  'addToWaitlist' : ActorMethod<[Email], boolean>,
  'cancelRecurringDeposit' : ActorMethod<[bigint], boolean>,
  'createVault' : ActorMethod<[CreateVaultRequest], bigint>,
  'emailAlreadyExists' : ActorMethod<[Email], boolean>,
  'getAchievements' : ActorMethod<[], Array<Achievement>>,
  'getDeadLetterJobs' : ActorMethod<[], Array<Job>>,
  'getEmailTimestamp' : ActorMethod<[string], [] | [Timestamp]>,
  'getGoalProgress' : ActorMethod<[bigint], GoalProgress>,
  'getGrowthAnalytics' : ActorMethod<[], GrowthAnalytics>,
  'getJobLog' : ActorMethod<[], Array<JobLogEntry>>,
  'getMetrics' : ActorMethod<[], AdminMetrics>,
  'getMilestones' : ActorMethod<[bigint], Array<ReachedMilestone>>,
  'getMyIdentity' : ActorMethod<[], UserIdentity>,
  'getMyPrincipal' : ActorMethod<[], string>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingJobCount' : ActorMethod<[], bigint>,
  'getRecommendationHistory' : ActorMethod<[], Array<Recommendation>>,
  'getRecommendations' : ActorMethod<[], Recommendation>,
  'getRecurringDeposits' : ActorMethod<[], Array<RecurringDeposit>>,
  'getVault' : ActorMethod<[bigint], [] | [VaultView]>,
  'getVaultLedger' : ActorMethod<[bigint], Array<LedgerEntry>>,
  'getVaultStats' : ActorMethod<[], Array<VaultStats>>,
  'getVaults' : ActorMethod<[], Array<VaultView>>,
  'getWaitlist' : ActorMethod<[], Array<Entry>>,
  'getWaitlistCount' : ActorMethod<[], bigint>,
  'isAdmin' : ActorMethod<[], boolean>,
  'makeDeposit' : ActorMethod<
    [bigint, bigint, IdempotencyKey, string],
    DepositResult
  >,
  'markAllNotificationsRead' : ActorMethod<[], bigint>,
  'markRead' : ActorMethod<[bigint], boolean>,
  'reconcileMyVaults' : ActorMethod<[], Array<ReconciliationResult>>,
  'reconcileVault' : ActorMethod<[bigint], ReconciliationResult>,
  'setupRecurringDeposit' : ActorMethod<[SetupRecurringDepositRequest], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];