/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface ReachedMilestone {
    percent: bigint;
    vaultId: bigint;
    milestone: Milestone;
    reachedAt: Timestamp;
}
export type Timestamp = bigint;
export type Sequence = bigint;
export type DepositResult = {
    __kind__: "ok";
    ok: {
        newBalance: bigint;
        transactionId: bigint;
    };
} | {
    __kind__: "insufficientReason";
    insufficientReason: null;
} | {
    __kind__: "duplicate";
    duplicate: null;
} | {
    __kind__: "invalidVault";
    invalidVault: null;
};
export interface LedgerEntry {
    idempotencyKey: IdempotencyKey;
    userId: UserId;
    side: EntrySide;
    description: string;
    triggeredBy: UserId;
    vaultId: bigint;
    timestamp: Timestamp;
    amount: bigint;
    sequence: Sequence;
    transactionId: bigint;
    reason: EntryReason;
}
export interface Achievement {
    id: bigint;
    title: string;
    userId: UserId;
    description: string;
    awardedAt: Timestamp;
}
export interface Job {
    id: bigint;
    status: JobStatus;
    idempotencyKey: IdempotencyKey;
    nextAttemptAt: Timestamp;
    kind: JobKind;
    createdAt: Timestamp;
    retryCount: bigint;
    lastError?: string;
    payload: string;
}
export interface VaultView {
    id: bigint;
    status: VaultStatus;
    unlockDate: Timestamp;
    goalName: string;
    note?: string;
    createdAt: Timestamp;
    progressPercent: bigint;
    targetAmount: bigint;
    currentAmount: bigint;
}
export interface Recommendation {
    id: bigint;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    rationale: string;
    cashFlowWarning?: string;
    disclaimer: string;
    suggestedPercent: bigint;
    suggestedDepositAdjustment?: {
        newAmount: bigint;
        vaultId: bigint;
    };
}
export interface RecurringDeposit {
    id: bigint;
    active: boolean;
    userId: UserId;
    createdAt: Timestamp;
    idempotencyKeyPrefix: IdempotencyKey;
    nextRunAt: Timestamp;
    vaultId: bigint;
    cadence: RecurringCadence;
    amount: bigint;
}
export interface GoalProgress {
    reachedMilestones: Array<Milestone>;
    percent: bigint;
    targetAmount: bigint;
    vaultId: bigint;
    currentAmount: bigint;
    nextMilestone?: Milestone;
}
export type Email = string;
export interface JobLogEntry {
    status: JobStatus;
    attempt: bigint;
    jobId: bigint;
    message: string;
    timestamp: Timestamp;
}
export interface GrowthAnalytics {
    newUsersLast30d: bigint;
    totalUsers: bigint;
    totalSavedAcrossVaults: bigint;
    averageVaultsPerUser: number;
    newUsersLast7d: bigint;
}
export interface VaultStats {
    status: string;
    depositCount: bigint;
    goalName: string;
    userId: UserId;
    targetAmount: bigint;
    vaultId: bigint;
    currentAmount: bigint;
}
export interface UserIdentity {
    principal: UserId;
    provider: IdentityProvider;
    isAdmin: boolean;
    registeredAt: Timestamp;
}
export interface SetupRecurringDepositRequest {
    idempotencyKeyPrefix: IdempotencyKey;
    vaultId: bigint;
    cadence: RecurringCadence;
    amount: bigint;
}
export type UserId = Principal;
export interface Entry {
    email: Email;
    timestamp: Timestamp;
}
export type IdempotencyKey = string;
export interface CreateVaultRequest {
    goalName: string;
    note?: string;
    lockDurationNs: Timestamp;
    targetAmount: bigint;
}
export interface Notification {
    id: bigint;
    title: string;
    body: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    vaultId?: bigint;
}
export interface AdminMetrics {
    deadLetterJobs: bigint;
    totalVaults: bigint;
    totalUsers: bigint;
    waitlistCount: bigint;
    pendingJobs: bigint;
    totalDeposits: bigint;
}
export interface ReconciliationResult {
    sumCredits: bigint;
    sumDebits: bigint;
    userId: UserId;
    vaultId: bigint;
    derivedBalance: bigint;
    balanced: boolean;
}
export enum EntryReason {
    recurringDeposit = "recurringDeposit",
    vaultLock = "vaultLock",
    interestReward = "interestReward",
    manualDeposit = "manualDeposit",
    vaultUnlock = "vaultUnlock",
    jobProcessing = "jobProcessing",
    withdrawal = "withdrawal",
    reconciliationAdjustment = "reconciliationAdjustment",
    vaultBreak = "vaultBreak"
}
export enum EntrySide {
    credit = "credit",
    debit = "debit"
}
export enum IdentityProvider {
    internetIdentity = "internetIdentity",
    apple = "apple",
    google = "google",
    email = "email"
}
export enum JobKind {
    unlockCheck = "unlockCheck",
    recurringDeposit = "recurringDeposit",
    interestReward = "interestReward",
    autoDeposit = "autoDeposit",
    optimizationRun = "optimizationRun",
    withdrawalProcess = "withdrawalProcess",
    milestoneCheck = "milestoneCheck"
}
export enum JobStatus {
    deadLetter = "deadLetter",
    pending = "pending",
    failed = "failed",
    running = "running",
    succeeded = "succeeded"
}
export enum Milestone {
    fifty = "fifty",
    seventyFive = "seventyFive",
    oneHundred = "oneHundred",
    twentyFive = "twentyFive"
}
export enum NotificationType {
    recommendationAvailable = "recommendationAvailable",
    unlockApproaching = "unlockApproaching",
    vaultUnlocked = "vaultUnlocked",
    milestoneReached = "milestoneReached",
    depositFrozen = "depositFrozen",
    adminBroadcast = "adminBroadcast"
}
export enum RecurringCadence {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum VaultStatus {
    broken = "broken",
    freezing = "freezing",
    thawed = "thawed",
    thawing = "thawing"
}
/**
 * / Froze backend — composition root.
 * /
 * / Wires all domain modules together via mixins. No business logic lives
 * / here; every public function is delegated to a mixin. Stable state is
 * / declared here and passed into the mixins that need it.
 * /
 * / State shape change from the previous waitlist-only actor requires an
 * / explicit migration (see migration.mo).
 */
export interface backendInterface {
    addAdmin(principal: UserId): Promise<boolean>;
    addToWaitlist(email: Email): Promise<boolean>;
    cancelRecurringDeposit(recurringId: bigint): Promise<boolean>;
    createVault(request: CreateVaultRequest): Promise<bigint>;
    emailAlreadyExists(email: Email): Promise<boolean>;
    getAchievements(): Promise<Array<Achievement>>;
    getDeadLetterJobs(): Promise<Array<Job>>;
    getEmailTimestamp(email: string): Promise<Timestamp | null>;
    getGoalProgress(vaultId: bigint): Promise<GoalProgress>;
    getGrowthAnalytics(): Promise<GrowthAnalytics>;
    getJobLog(): Promise<Array<JobLogEntry>>;
    getMetrics(): Promise<AdminMetrics>;
    getMilestones(vaultId: bigint): Promise<Array<ReachedMilestone>>;
    getMyIdentity(): Promise<UserIdentity>;
    getMyPrincipal(): Promise<string>;
    getNotifications(): Promise<Array<Notification>>;
    getPendingJobCount(): Promise<bigint>;
    getRecommendationHistory(): Promise<Array<Recommendation>>;
    getRecommendations(): Promise<Recommendation>;
    getRecurringDeposits(): Promise<Array<RecurringDeposit>>;
    getVault(vaultId: bigint): Promise<VaultView | null>;
    getVaultLedger(vaultId: bigint): Promise<Array<LedgerEntry>>;
    getVaultStats(): Promise<Array<VaultStats>>;
    getVaults(): Promise<Array<VaultView>>;
    getWaitlist(): Promise<Array<Entry>>;
    getWaitlistCount(): Promise<bigint>;
    isAdmin(): Promise<boolean>;
    makeDeposit(vaultId: bigint, amount: bigint, idempotencyKey: IdempotencyKey, description: string): Promise<DepositResult>;
    markAllNotificationsRead(): Promise<bigint>;
    markRead(notificationId: bigint): Promise<boolean>;
    reconcileMyVaults(): Promise<Array<ReconciliationResult>>;
    reconcileVault(vaultId: bigint): Promise<ReconciliationResult>;
    setupRecurringDeposit(request: SetupRecurringDepositRequest): Promise<bigint>;
}
import type { CreateVaultRequest as _CreateVaultRequest, DepositResult as _DepositResult, EntryReason as _EntryReason, EntrySide as _EntrySide, GoalProgress as _GoalProgress, IdempotencyKey as _IdempotencyKey, IdentityProvider as _IdentityProvider, Job as _Job, JobKind as _JobKind, JobLogEntry as _JobLogEntry, JobStatus as _JobStatus, LedgerEntry as _LedgerEntry, Milestone as _Milestone, Notification as _Notification, NotificationType as _NotificationType, ReachedMilestone as _ReachedMilestone, Recommendation as _Recommendation, RecurringCadence as _RecurringCadence, RecurringDeposit as _RecurringDeposit, Sequence as _Sequence, SetupRecurringDepositRequest as _SetupRecurringDepositRequest, Timestamp as _Timestamp, UserId as _UserId, UserIdentity as _UserIdentity, VaultStatus as _VaultStatus, VaultView as _VaultView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async addToWaitlist(arg0: Email): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWaitlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWaitlist(arg0);
            return result;
        }
    }
    async cancelRecurringDeposit(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelRecurringDeposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelRecurringDeposit(arg0);
            return result;
        }
    }
    async createVault(arg0: CreateVaultRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVault(to_candid_CreateVaultRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVault(to_candid_CreateVaultRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async emailAlreadyExists(arg0: Email): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.emailAlreadyExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.emailAlreadyExists(arg0);
            return result;
        }
    }
    async getAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAchievements();
            return result;
        }
    }
    async getDeadLetterJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeadLetterJobs();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeadLetterJobs();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmailTimestamp(arg0: string): Promise<Timestamp | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailTimestamp(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailTimestamp(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoalProgress(arg0: bigint): Promise<GoalProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoalProgress(arg0);
                return from_candid_GoalProgress_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoalProgress(arg0);
            return from_candid_GoalProgress_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrowthAnalytics(): Promise<GrowthAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrowthAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrowthAnalytics();
            return result;
        }
    }
    async getJobLog(): Promise<Array<JobLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobLog();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobLog();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMetrics(): Promise<AdminMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async getMilestones(arg0: bigint): Promise<Array<ReachedMilestone>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilestones(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilestones(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyIdentity(): Promise<UserIdentity> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyIdentity();
                return from_candid_UserIdentity_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyIdentity();
            return from_candid_UserIdentity_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPrincipal(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPrincipal();
            return result;
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingJobCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingJobCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingJobCount();
            return result;
        }
    }
    async getRecommendationHistory(): Promise<Array<Recommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendationHistory();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendationHistory();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendations(): Promise<Recommendation> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendations();
                return from_candid_Recommendation_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendations();
            return from_candid_Recommendation_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecurringDeposits(): Promise<Array<RecurringDeposit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecurringDeposits();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecurringDeposits();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVault(arg0: bigint): Promise<VaultView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVault(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVault(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVaultLedger(arg0: bigint): Promise<Array<LedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaultLedger(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaultLedger(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVaultStats(): Promise<Array<VaultStats>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaultStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaultStats();
            return result;
        }
    }
    async getVaults(): Promise<Array<VaultView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVaults();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVaults();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWaitlist(): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitlist();
            return result;
        }
    }
    async getWaitlistCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWaitlistCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWaitlistCount();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async makeDeposit(arg0: bigint, arg1: bigint, arg2: IdempotencyKey, arg3: string): Promise<DepositResult> {
        if (this.processError) {
            try {
                const result = await this.actor.makeDeposit(arg0, arg1, arg2, arg3);
                return from_candid_DepositResult_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeDeposit(arg0, arg1, arg2, arg3);
            return from_candid_DepositResult_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markRead(arg0);
            return result;
        }
    }
    async reconcileMyVaults(): Promise<Array<ReconciliationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.reconcileMyVaults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reconcileMyVaults();
            return result;
        }
    }
    async reconcileVault(arg0: bigint): Promise<ReconciliationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.reconcileVault(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reconcileVault(arg0);
            return result;
        }
    }
    async setupRecurringDeposit(arg0: SetupRecurringDepositRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.setupRecurringDeposit(to_candid_SetupRecurringDepositRequest_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupRecurringDeposit(to_candid_SetupRecurringDepositRequest_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DepositResult_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositResult): DepositResult {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_EntryReason_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntryReason): EntryReason {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_EntrySide_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntrySide): EntrySide {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_GoalProgress_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalProgress): GoalProgress {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_IdentityProvider_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IdentityProvider): IdentityProvider {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_JobKind_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobKind): JobKind {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_JobLogEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobLogEntry): JobLogEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_LedgerEntry_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LedgerEntry): LedgerEntry {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Milestone_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Milestone): Milestone {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ReachedMilestone_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReachedMilestone): ReachedMilestone {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringCadence_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringCadence): RecurringCadence {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_RecurringDeposit_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RecurringDeposit): RecurringDeposit {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserIdentity_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserIdentity): UserIdentity {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_VaultStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VaultStatus): VaultStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_VaultView_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VaultView): VaultView {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Milestone]): Milestone | null {
    return value.length === 0 ? null : from_candid_Milestone_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        newAmount: bigint;
        vaultId: bigint;
    }]): {
    newAmount: bigint;
    vaultId: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VaultView]): VaultView | null {
    return value.length === 0 ? null : from_candid_VaultView_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reachedMilestones: Array<_Milestone>;
    percent: bigint;
    targetAmount: bigint;
    vaultId: bigint;
    currentAmount: bigint;
    nextMilestone: [] | [_Milestone];
}): {
    reachedMilestones: Array<Milestone>;
    percent: bigint;
    targetAmount: bigint;
    vaultId: bigint;
    currentAmount: bigint;
    nextMilestone?: Milestone;
} {
    return {
        reachedMilestones: from_candid_vec_n14(_uploadFile, _downloadFile, value.reachedMilestones),
        percent: value.percent,
        targetAmount: value.targetAmount,
        vaultId: value.vaultId,
        currentAmount: value.currentAmount,
        nextMilestone: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.nextMilestone))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _JobStatus;
    attempt: bigint;
    jobId: bigint;
    message: string;
    timestamp: _Timestamp;
}): {
    status: JobStatus;
    attempt: bigint;
    jobId: bigint;
    message: string;
    timestamp: Timestamp;
} {
    return {
        status: from_candid_JobStatus_n6(_uploadFile, _downloadFile, value.status),
        attempt: value.attempt,
        jobId: value.jobId,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    percent: bigint;
    vaultId: bigint;
    milestone: _Milestone;
    reachedAt: _Timestamp;
}): {
    percent: bigint;
    vaultId: bigint;
    milestone: Milestone;
    reachedAt: Timestamp;
} {
    return {
        percent: value.percent,
        vaultId: value.vaultId,
        milestone: from_candid_Milestone_n15(_uploadFile, _downloadFile, value.milestone),
        reachedAt: value.reachedAt
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    provider: _IdentityProvider;
    isAdmin: boolean;
    registeredAt: _Timestamp;
}): {
    principal: UserId;
    provider: IdentityProvider;
    isAdmin: boolean;
    registeredAt: Timestamp;
} {
    return {
        principal: value.principal,
        provider: from_candid_IdentityProvider_n26(_uploadFile, _downloadFile, value.provider),
        isAdmin: value.isAdmin,
        registeredAt: value.registeredAt
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    body: string;
    userId: _UserId;
    notificationType: _NotificationType;
    createdAt: _Timestamp;
    read: boolean;
    vaultId: [] | [bigint];
}): {
    id: bigint;
    title: string;
    body: string;
    userId: UserId;
    notificationType: NotificationType;
    createdAt: Timestamp;
    read: boolean;
    vaultId?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n31(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        read: value.read,
        vaultId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.vaultId))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    userId: _UserId;
    createdAt: _Timestamp;
    rationale: string;
    cashFlowWarning: [] | [string];
    disclaimer: string;
    suggestedPercent: bigint;
    suggestedDepositAdjustment: [] | [{
            newAmount: bigint;
            vaultId: bigint;
        }];
}): {
    id: bigint;
    title: string;
    userId: UserId;
    createdAt: Timestamp;
    rationale: string;
    cashFlowWarning?: string;
    disclaimer: string;
    suggestedPercent: bigint;
    suggestedDepositAdjustment?: {
        newAmount: bigint;
        vaultId: bigint;
    };
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        createdAt: value.createdAt,
        rationale: value.rationale,
        cashFlowWarning: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.cashFlowWarning)),
        disclaimer: value.disclaimer,
        suggestedPercent: value.suggestedPercent,
        suggestedDepositAdjustment: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.suggestedDepositAdjustment))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    userId: _UserId;
    createdAt: _Timestamp;
    idempotencyKeyPrefix: _IdempotencyKey;
    nextRunAt: _Timestamp;
    vaultId: bigint;
    cadence: _RecurringCadence;
    amount: bigint;
}): {
    id: bigint;
    active: boolean;
    userId: UserId;
    createdAt: Timestamp;
    idempotencyKeyPrefix: IdempotencyKey;
    nextRunAt: Timestamp;
    vaultId: bigint;
    cadence: RecurringCadence;
    amount: bigint;
} {
    return {
        id: value.id,
        active: value.active,
        userId: value.userId,
        createdAt: value.createdAt,
        idempotencyKeyPrefix: value.idempotencyKeyPrefix,
        nextRunAt: value.nextRunAt,
        vaultId: value.vaultId,
        cadence: from_candid_RecurringCadence_n41(_uploadFile, _downloadFile, value.cadence),
        amount: value.amount
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _VaultStatus;
    unlockDate: _Timestamp;
    goalName: string;
    note: [] | [string];
    createdAt: _Timestamp;
    progressPercent: bigint;
    targetAmount: bigint;
    currentAmount: bigint;
}): {
    id: bigint;
    status: VaultStatus;
    unlockDate: Timestamp;
    goalName: string;
    note?: string;
    createdAt: Timestamp;
    progressPercent: bigint;
    targetAmount: bigint;
    currentAmount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_VaultStatus_n46(_uploadFile, _downloadFile, value.status),
        unlockDate: value.unlockDate,
        goalName: value.goalName,
        note: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt,
        progressPercent: value.progressPercent,
        targetAmount: value.targetAmount,
        currentAmount: value.currentAmount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _JobStatus;
    idempotencyKey: _IdempotencyKey;
    nextAttemptAt: _Timestamp;
    kind: _JobKind;
    createdAt: _Timestamp;
    retryCount: bigint;
    lastError: [] | [string];
    payload: string;
}): {
    id: bigint;
    status: JobStatus;
    idempotencyKey: IdempotencyKey;
    nextAttemptAt: Timestamp;
    kind: JobKind;
    createdAt: Timestamp;
    retryCount: bigint;
    lastError?: string;
    payload: string;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n6(_uploadFile, _downloadFile, value.status),
        idempotencyKey: value.idempotencyKey,
        nextAttemptAt: value.nextAttemptAt,
        kind: from_candid_JobKind_n8(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        retryCount: value.retryCount,
        lastError: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.lastError)),
        payload: value.payload
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idempotencyKey: _IdempotencyKey;
    userId: _UserId;
    side: _EntrySide;
    description: string;
    triggeredBy: _UserId;
    vaultId: bigint;
    timestamp: _Timestamp;
    amount: bigint;
    sequence: _Sequence;
    transactionId: bigint;
    reason: _EntryReason;
}): {
    idempotencyKey: IdempotencyKey;
    userId: UserId;
    side: EntrySide;
    description: string;
    triggeredBy: UserId;
    vaultId: bigint;
    timestamp: Timestamp;
    amount: bigint;
    sequence: Sequence;
    transactionId: bigint;
    reason: EntryReason;
} {
    return {
        idempotencyKey: value.idempotencyKey,
        userId: value.userId,
        side: from_candid_EntrySide_n51(_uploadFile, _downloadFile, value.side),
        description: value.description,
        triggeredBy: value.triggeredBy,
        vaultId: value.vaultId,
        timestamp: value.timestamp,
        amount: value.amount,
        sequence: value.sequence,
        transactionId: value.transactionId,
        reason: from_candid_EntryReason_n53(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fifty: null;
} | {
    seventyFive: null;
} | {
    oneHundred: null;
} | {
    twentyFive: null;
}): Milestone {
    return "fifty" in value ? Milestone.fifty : "seventyFive" in value ? Milestone.seventyFive : "oneHundred" in value ? Milestone.oneHundred : "twentyFive" in value ? Milestone.twentyFive : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    internetIdentity: null;
} | {
    apple: null;
} | {
    google: null;
} | {
    email: null;
}): IdentityProvider {
    return "internetIdentity" in value ? IdentityProvider.internetIdentity : "apple" in value ? IdentityProvider.apple : "google" in value ? IdentityProvider.google : "email" in value ? IdentityProvider.email : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recommendationAvailable: null;
} | {
    unlockApproaching: null;
} | {
    vaultUnlocked: null;
} | {
    milestoneReached: null;
} | {
    depositFrozen: null;
} | {
    adminBroadcast: null;
}): NotificationType {
    return "recommendationAvailable" in value ? NotificationType.recommendationAvailable : "unlockApproaching" in value ? NotificationType.unlockApproaching : "vaultUnlocked" in value ? NotificationType.vaultUnlocked : "milestoneReached" in value ? NotificationType.milestoneReached : "depositFrozen" in value ? NotificationType.depositFrozen : "adminBroadcast" in value ? NotificationType.adminBroadcast : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): RecurringCadence {
    return "monthly" in value ? RecurringCadence.monthly : "daily" in value ? RecurringCadence.daily : "weekly" in value ? RecurringCadence.weekly : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    broken: null;
} | {
    freezing: null;
} | {
    thawed: null;
} | {
    thawing: null;
}): VaultStatus {
    return "broken" in value ? VaultStatus.broken : "freezing" in value ? VaultStatus.freezing : "thawed" in value ? VaultStatus.thawed : "thawing" in value ? VaultStatus.thawing : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): EntrySide {
    return "credit" in value ? EntrySide.credit : "debit" in value ? EntrySide.debit : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recurringDeposit: null;
} | {
    vaultLock: null;
} | {
    interestReward: null;
} | {
    manualDeposit: null;
} | {
    vaultUnlock: null;
} | {
    jobProcessing: null;
} | {
    withdrawal: null;
} | {
    reconciliationAdjustment: null;
} | {
    vaultBreak: null;
}): EntryReason {
    return "recurringDeposit" in value ? EntryReason.recurringDeposit : "vaultLock" in value ? EntryReason.vaultLock : "interestReward" in value ? EntryReason.interestReward : "manualDeposit" in value ? EntryReason.manualDeposit : "vaultUnlock" in value ? EntryReason.vaultUnlock : "jobProcessing" in value ? EntryReason.jobProcessing : "withdrawal" in value ? EntryReason.withdrawal : "reconciliationAdjustment" in value ? EntryReason.reconciliationAdjustment : "vaultBreak" in value ? EntryReason.vaultBreak : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        newBalance: bigint;
        transactionId: bigint;
    };
} | {
    insufficientReason: null;
} | {
    duplicate: null;
} | {
    invalidVault: null;
}): {
    __kind__: "ok";
    ok: {
        newBalance: bigint;
        transactionId: bigint;
    };
} | {
    __kind__: "insufficientReason";
    insufficientReason: null;
} | {
    __kind__: "duplicate";
    duplicate: null;
} | {
    __kind__: "invalidVault";
    invalidVault: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "insufficientReason" in value ? {
        __kind__: "insufficientReason",
        insufficientReason: value.insufficientReason
    } : "duplicate" in value ? {
        __kind__: "duplicate",
        duplicate: value.duplicate
    } : "invalidVault" in value ? {
        __kind__: "invalidVault",
        invalidVault: value.invalidVault
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deadLetter: null;
} | {
    pending: null;
} | {
    failed: null;
} | {
    running: null;
} | {
    succeeded: null;
}): JobStatus {
    return "deadLetter" in value ? JobStatus.deadLetter : "pending" in value ? JobStatus.pending : "failed" in value ? JobStatus.failed : "running" in value ? JobStatus.running : "succeeded" in value ? JobStatus.succeeded : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unlockCheck: null;
} | {
    recurringDeposit: null;
} | {
    interestReward: null;
} | {
    autoDeposit: null;
} | {
    optimizationRun: null;
} | {
    withdrawalProcess: null;
} | {
    milestoneCheck: null;
}): JobKind {
    return "unlockCheck" in value ? JobKind.unlockCheck : "recurringDeposit" in value ? JobKind.recurringDeposit : "interestReward" in value ? JobKind.interestReward : "autoDeposit" in value ? JobKind.autoDeposit : "optimizationRun" in value ? JobKind.optimizationRun : "withdrawalProcess" in value ? JobKind.withdrawalProcess : "milestoneCheck" in value ? JobKind.milestoneCheck : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Milestone>): Array<Milestone> {
    return value.map((x)=>from_candid_Milestone_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobLogEntry>): Array<JobLogEntry> {
    return value.map((x)=>from_candid_JobLogEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReachedMilestone>): Array<ReachedMilestone> {
    return value.map((x)=>from_candid_ReachedMilestone_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Recommendation>): Array<Recommendation> {
    return value.map((x)=>from_candid_Recommendation_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RecurringDeposit>): Array<RecurringDeposit> {
    return value.map((x)=>from_candid_RecurringDeposit_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LedgerEntry>): Array<LedgerEntry> {
    return value.map((x)=>from_candid_LedgerEntry_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VaultView>): Array<VaultView> {
    return value.map((x)=>from_candid_VaultView_n44(_uploadFile, _downloadFile, x));
}
function to_candid_CreateVaultRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateVaultRequest): _CreateVaultRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RecurringCadence_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringCadence): _RecurringCadence {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_SetupRecurringDepositRequest_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SetupRecurringDepositRequest): _SetupRecurringDepositRequest {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalName: string;
    note?: string;
    lockDurationNs: Timestamp;
    targetAmount: bigint;
}): {
    goalName: string;
    note: [] | [string];
    lockDurationNs: _Timestamp;
    targetAmount: bigint;
} {
    return {
        goalName: value.goalName,
        note: value.note ? candid_some(value.note) : candid_none(),
        lockDurationNs: value.lockDurationNs,
        targetAmount: value.targetAmount
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idempotencyKeyPrefix: IdempotencyKey;
    vaultId: bigint;
    cadence: RecurringCadence;
    amount: bigint;
}): {
    idempotencyKeyPrefix: _IdempotencyKey;
    vaultId: bigint;
    cadence: _RecurringCadence;
    amount: bigint;
} {
    return {
        idempotencyKeyPrefix: value.idempotencyKeyPrefix,
        vaultId: value.vaultId,
        cadence: to_candid_RecurringCadence_n60(_uploadFile, _downloadFile, value.cadence),
        amount: value.amount
    };
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecurringCadence): {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == RecurringCadence.monthly ? {
        monthly: null
    } : value == RecurringCadence.daily ? {
        daily: null
    } : value == RecurringCadence.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
